name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm frustrated when... It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see... This could work by...
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New tool (new API endpoint category)
        - New action (additional action for existing tool)
        - Enhancement (improvement to existing feature)
        - Performance improvement
        - Developer experience
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: affected-tool
    attributes:
      label: Which tool would this affect?
      description: If applicable, which tool would benefit from this feature?
      options:
        - uw_stock
        - uw_options
        - uw_market
        - uw_flow
        - uw_darkpool
        - uw_congress
        - uw_insider
        - uw_institutions
        - uw_earnings
        - uw_etf
        - uw_screener
        - uw_shorts
        - uw_seasonality
        - uw_news
        - uw_alerts
        - uw_politicians
        - Multiple tools
        - New tool (not listed)
        - Core infrastructure
        - Not tool-specific

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: I also thought about... Another approach could be...

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Provide examples of how this feature would be used
      placeholder: |
        Example 1: Get insider trades with filters
        {
          "action": "transactions",
          "ticker": "AAPL",
          "min_value": 1000000
        }

        Example 2: ...
      render: json

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my use case)
        - High (would significantly improve my workflow)
        - Medium (nice to have)
        - Low (minor convenience)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case in detail
      placeholder: |
        I'm building... and need to...
        This would help me...
    validations:
      required: true

  - type: dropdown
    id: api-support
    attributes:
      label: API Support
      description: Does the Unusual Whales API already support this?
      options:
        - "Yes, API supports this (just needs MCP integration)"
        - "No, would require new API endpoint"
        - "Unsure"
        - "N/A (not API-related)"
    validations:
      required: true

  - type: textarea
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this require breaking changes to existing functionality?
      placeholder: |
        - Would this change existing behavior?
        - Would existing code need to be updated?
        - How could we maintain backwards compatibility?

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      placeholder: |
        This could be implemented by...
        Technical approach...
        Potential challenges...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
      placeholder: |
        - Similar features in other tools
        - Links to relevant documentation
        - Screenshots or mockups

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would be willing to submit a PR for this feature
          required: false
        - label: I can help with testing this feature
          required: false
        - label: I can help with documentation for this feature
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have checked the Unusual Whales API docs to see if this is supported
          required: false
        - label: I have considered backwards compatibility
          required: true
